theme: jekyll-theme-dinky
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # Use our default layout (with navigation) on all pages
title: "NLP 2021"
description: "Assignments for NLP course, Computer Science, University of Helsinki"
markdown: kramdown
